### ISSUE TITLE
Can this be deployed using a YAML pipeline from AzureDevOps

### ISSUE THREAD

**Issue by MikeAtETI** [staticwebdev/blazor-starter#16]
Is it possible to deploy this from AzureDevOps?

**Comment by mejohnsonjr** [comment]
@MikeAtETI you can follow this tutorial to deploy this template from Azure DevOps: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-devops

You'll just need to update the the app_location, api_location, and output_location in the yaml file provided in the tutorial.

If you didn't rename any of the projects in the template, you should be able to use these values:
app_location: 'Client'
api_location: 'Api'
output_location: 'wwwroot'

**Comment by aaronpowell** [comment]
@mejohnsonjr is on the money there. Static Web Apps supports both GitHub Actions and Azure DevOps for deployment.
