### ISSUE TITLE
.NET 6.0 for API Functions App 

### ISSUE THREAD

**Issue by dotnetnoobie** [staticwebdev/blazor-starter#17]
Currently .NET 6.0 works for the Client app

But I am not able to make .NET 6.0 work for the Functions API app

Is there a way to tell the GitHub action that it needs to upgrade the Functions API app to .NET 6.0 as I see described in some docs about how to use .NET 6.0 preview in Functions Apps from this link [What’s new with .NET on Azure Functions – June 2021](https://techcommunity.microsoft.com/t5/apps-on-azure/what-s-new-with-net-on-azure-functions-june-2021/ba-p/2428669)

**Comment by aaronpowell** [comment]
Azure Static Web Apps currently only supports .NET 3.1 (see [the docs on API support](https://docs.microsoft.com/azure/static-web-apps/apis?WT.mc_id=dotnet-0000-aapowell)).

If you want to use another form of Azure Functions, you'll need to use [bring your own Functions](https://docs.microsoft.com/azure/static-web-apps/functions-bring-your-own?WT.mc_id=dotnet-0000-aapowell) which is available on the [Standard Tier](https://azure.microsoft.com/pricing/details/app-service/static/?WT.mc_id=dotnet-0000-aapowell#pricing).

I'd suggest following [this issue](https://github.com/Azure/static-web-apps/issues/445) for more indication of when other .NET runtimes are supported.
