### ISSUE TITLE
Could not load type 'System.Random' from assembly 'System.Runtime, Version=4.2.2.0

### ISSUE THREAD

**Issue by pmeems** [staticwebdev/blazor-starter#24]
Sadly this template is not working out of the box anymore.
After merging the pull requests I was finally able to compile the solution.

After running the webapp I get this error when calling the Azure Function:
`Could not load type 'System.Random' from assembly 'System.Runtime, Version=4.2.2.0`

I can't find how to fix this.
I've used the template before with .NET3.1 and that worked fine.
Very sad that the template is no longer working after updating to .NET6.
I wonder how this template is tested ;)

**Comment by markjackmilian** [comment]
I also had your error. I solved it by upgrading to azure-functions-core-tools@4.

Try running:
npm i -g azure-functions-core-tools@4 --unsafe-perm true

**Comment by pmeems** [comment]
Thanks that solved my problem.
I already assumed it was something on my laptop, because after deploying to Azure everything did work.

I also have issues with debugging (not breaking) and hot reload.
Perhaps I need to reinstall my system ;(
