### ISSUE TITLE
Playwright 'storeReports' job failure

### ISSUE THREAD

**Issue by skipleam** [staticwebdev/blazor-starter#35]
In the Playwright tests, the `storeReports` job attempts to publish into a MSFT intern project repository ([here](https://github.com/staticwebdev/blazor-starter/blob/f35c0bd29c82b53deb268e383e6324644922328e/.github/workflows/playwright-onDemand.yml#L69)).  
Is there guidance around configuring this job when using this repo as a template? Should it be deleted for the general public?

**Comment by anthonychu** [comment]
We'll be removing the tests in #38. Thanks for letting us know.
