### ISSUE TITLE
Integrate test run

### ISSUE THREAD

**Issue by gkfischer** [staticwebdev/blazor-starter#4]
Probably because I'm new to Github actions, but I can't figure out how to integrate unit tests in this template. The normal steps like setup, restore and build aren't viisble and so I'm at a loss how to do that. Any suggestions, docs, hints or solutions?

**Comment by aaronpowell** [comment]
There's two ways that you can tackle this.

The first would be to add build and test jobs into the Actions workflow before it does the build and deploy to Azure using the Static Web Apps action. I _kind of_ do that [here](https://github.com/aaronpowell/react-foldable/blob/main/.github/workflows/azure-static-web-apps-white-stone-064a8bf0f.yml#L13-L33) (although with `npm` commands, not `dotnet` commands), but you can see how you can modify the workflow file to do anything you want.

The other option would be to specify a [custom build command](https://docs.microsoft.com/azure/static-web-apps/github-actions-workflow?WT.mc_id=dotnet-github-aapowell#custom-build-commands) that executes the build/test/publish command.

**Comment by staticwebdev** [comment]
Closing this as @aaronpowell provided a suggestions on how to run tests.
