### ISSUE TITLE
VSCode: Only Starts Azure Functions, not Blazor WebAssembly

### ISSUE THREAD

**Issue by JustinGrote** [staticwebdev/blazor-starter#6]
When running the default task with vscode, it only starts and attaches to Azure Functions backend, it does not start the webassembly frontend

I had to initiate a separate window and define this task
```
    {
      "name": "Start Blazor",
      "type": "blazorwasm",
      "request": "launch",
      "cwd": "${workspaceFolder}/Client",
      "browser": "edge"
    }
```

And start it to then be able to use the webapp.

Is it possible to start/debug both simultaneously without doing two separate VSCode windows?

**Comment by JustinGrote** [comment]
I addressed my concern with the compound launch task from https://github.com/staticwebdev/blazor-starter/pull/5/commits/5dc0e89d7717a83d12e35765699412c8066d8ceb and recommend this PR be merged.

**Comment by staticwebdev** [comment]
Thanks, @JustinGrote

the PR is now merged.
