### ISSUE TITLE
Request: blazor-starter template using net5.0

### ISSUE THREAD

**Issue by kaeaddaar** [staticwebdev/blazor-starter#7]
An upgraded blazor-starter template running on .Net 5.0 would be very nice. It is easy to take a wrong turn when updating to net5.0 preventing things from running.

**Comment by vangelkolarov-actioncamvideo** [comment]
Azure Functions still does not support .NET 5: https://techcommunity.microsoft.com/t5/apps-on-azure/net-5-support-on-azure-functions/ba-p/1973055

**Comment by staticwebdev** [comment]
Closing this issue as Azure Functions and therefore Azure Static Web Apps is yet to support .NET 5.0.
