### ISSUE TITLE
Update Client to support Blazor with .NET 5

### ISSUE THREAD

**Issue by csharpfritz** [staticwebdev/blazor-starter#8]
It would be great to run the .NET 5 version of Blazor Web Assembly in the `Client` project, connecting to Azure Functions running on .NET Core 3.1 in the `Api` project

**Comment by aaronpowell** [comment]
Are there any major compatibility issues that someone is likely to hit if they were to try and do code sharing across the .NET versions? I'm just thinking through whether we need anything documented around this until Functions supports .NET 5.
